export const EndPoints = {
  register: 'register',
  login: 'login',
  forgotpassword: 'forgotpassword',
  forgotpasswordotp: 'forgotpasswordotp',
  resetpassword: 'resetpassword',
  verifyRegisterOtp: 'verify-register-otp',
  resendotp: 'resend-otp',
  addreceiver: 'addreceivers',
  fetchReceivers: 'receivers/getMyReceivers',
  fetchReceiver: 'receiver/',
  updateReceiver: 'receiver/update/',
  fetchFollowUpsByReceiverId: 'followups/receiver/',
  removeReceiver: 'receiver/destroy/',
  followupByMonth: 'followups/monthly-followups?',
  addNewFollowUp: 'addfollowups',
  followUpByFollowUpId: 'followup/',
  deleteFollowUp: 'followup/destroy/',
  logOut: 'user/logout',
};
